name: Code-Checks-Remote
on:
  push:
    branches:
      - master 
      - main
    paths-ignore:
      - README.md
      - .old_cicd/*
      # - .github/*
      # - .github/workflows/*
      - LICENSE
      - .gitignore
      - .dockerignore
      - .githooks
    tags-ignore:
      - 'v[0-9]+.[0-9]+.*'
jobs:
  build-push-release:
    uses: pchachicho/renci-github-actions/.github/workflows/code-checks.yml@main
    # secrets: inherit