name: upload-pypi
run-name: Package and Upload to Pypi  
on:
  workflow_call:
  push:
    branches:
      - master
      - main
    # paths-ignore:
    #   - README.md
    #   - .old_cicd/*
    #   - .github/*
    #   - .github/workflows/*
    #   - LICENSE
    #   - .gitignore
    #   - .dockerignore
      - .githooks
    tags:
      - 'v[0-9]+.[0-9]+.*'
jobs:
  build-deploy-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Package Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine

      - name: Build Package
        run: python -m build
      - name: Publish Package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
