name: Fetch OWASP Top 10

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-owasp-top-ten:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Fetch OWASP Top 10
      run: |
        touch owasp_top_ten.txt
        python .github/fetch_owasp_top_ten.py
        cat .github/pull_request_template.md


      # - name: Update PR template
    #   run: |
    #     owasp_top_ten=$(cat owasp_top_ten.txt | awk '{print "- " $0}' | paste -sd '\n' -)
    #     echo "OWASP Top Ten:"
    #     echo "$owasp_top_ten"
    #     echo "Debug: escaping special characters"
    #     printf '%s' "$owasp_top_ten" | sed 's/[&/\]/\\&/g'  
    #     sed -i "s|\[The OWASP Top Ten list will be fetched and updated by a GitHub Action.\]|$owasp_top_ten|" .github/pull_request_template.md
    #     echo "Updated PR Template:"

    - name: Clean up
      run: |
        rm owasp_top_ten.txt

    - name: Commit and push changes to a new branch
      env: 
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "pchachicho"
        git config --global user.email "hachichopatrick@gmail.com"
        
        # Create a new branch
        branch_name="update-owasp-top-ten-$(date +'%Y%m%d%H%M%S')"
        git checkout -b $branch_name
        
        # Add changes
        git add .github/pull_request_template.md
        git commit -m "Update PR template with latest OWASP Top Ten"
        
        # Push to new branch
        git push -u origin $branch_name

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_PAT }}
        branch: $branch_name
        title: "Update PR template with latest OWASP Top Ten"
        body: "This PR updates the PR template with the latest OWASP Top Ten."
        base: main
