name: Update PR Template

on:
  schedule:
    - cron: '0 0 * * 1' # This runs the action every Monday at midnight
  workflow_dispatch: # This allows you to run the workflow manually

jobs:
  update-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch OWASP Top Ten
        id: fetch_owasp
        run: |
          curl -s https://owasp.org/www-project-top-ten/ | grep -oP '(?<=<h2>Top 10:)[^<]+' | head -n 10 > owasp_top_ten.txt

      - name: Print Directory Contents
        run: |
         echo "Printing repository directory structure:"
         ls -R
         echo "Printing .github directory contents:"
         ls -R .github

      - name: Update PR template
        run: |
          owasp_top_ten=$(cat owasp_top_ten.txt | awk '{print "- " $0}' | paste -sd '\n' -)
          sed -i "s|\[The OWASP Top Ten list will be fetched and updated by a GitHub Action.\]|$owasp_top_ten|" .github/PULL_REQUEST_TEMPLATE.md

      - name: Commit and push changes
        run: |
          git config --global user.name "pchachicho"
          git config --global user.email "hachichopatrick@gmail.com"
          git add .github/PULL_REQUEST_TEMPLATE.md
          git commit -m "Update PR template with latest OWASP Top Ten"
          git push
